export const ServiceApi = [
  {
    id: 1,
    key: "go online",
    title: "START YOUR ONLINE JOURNEY WITH US",
    desc: "Web Guruji Will Help You To Take Your Offline Dream Project To Online By Building A New Online Web Based Application And Make It Online And Access It Anytime You Need From Anywhere In The World.",
    img: "/aeps.png",
    redirect: "pageonline",

  },
  {
    id: 2,
    key: "Get On Top Search",
    title: "Get on Top Searchable Result",
    desc: "Web Guru Ji is a Smart Online Development Project where the projects are developed in a compact manner, which will help you to find it on top searchable results compared to other web based project.",
    img: "/aeps.png",
    redirect: "pagesearch",
  },
  {
    id: 3,
    key: "Grab Online Customer",
    title: "Domestic Money Transfer (DMT)",
    desc: "With ThanksPay you have the opportunity to start money transfer business and transfer cash from your outlet to any Bank Account across the country with least charges in the industry, leading to a high income opportunity for all our money transfer agents. On every transaction, the retailer can earn a handsome income.",
    img: "/aeps.png",
    redirect: "pagecustomer",
  },
  {
    id: 4,
    key: "Build Dream Project",
    title: "UPI, QR Code, MPOS, Aadhar Pay",
    desc: "ThanksPay partners can offer multiple Payment options for the convenience of their customers- a unique UPI & QR Code where customer can pay by scanning, MPOS for Debit/Credit Card Swipe, Payment Link for online payment and Aadhaar Pay where customers can pay using their Aadhaar card and many more.",
    img: "/miniatm.png",
    redirect: "pagedream",
  },
  {
    id: 5,
    key: "Why Not Single Page",
    title: "Recharge, Bill Payments, PAN Card",
    desc: "Customer Mobile and DTH Recharge, Electricity, Gas and 30+ such bill payments, PAN Card Creation services are offered in ThanksPay panel to help the partner attract more customers and increase their service portfolio while earning money on each transaction",
    img: "/util2.png",
    redirect: "pagesinglepage",
  },
  {
    id: 6,
    key: "Talk with Experts",
    title: "Risk Free Guaranteed Returns",
    desc: "Ensuring Risk free guaranteed returns, ThanksPay introduces an Insurance Saving plan with 25 times cover. Get more returns than any savings account on the amount invested. ThanksPay partners will add to their income and help customers fulfil their dreams with the savings plan.",
    img: "/util.png",
    redirect: "pageexperts",
  },
  {
    id: 7,
    key: "Lets Build Your Dream",
    title: "Debit Card without Account",
    desc: "Using the ThanksPay Prepaid card, ThanksPay partners can provide debit cards to customers who do not own a bank account. Customers can use these cards to pay for purchases like any normal debit card.",
    img: "/payment.png",
    redirect: "pagebuilddream",
  },
];
